### ISSUE TITLE
Add module interaction diagram to readme

### ISSUE THREAD

**Issue by karntrehan** [Samagra-Development/dsep#31]
https://github.com/beckn/DSEP-Specification/discussions mentions the 4 modules that DSEP should contain. 

* Diverse use cases for Jobs and Internships
* Diverse use cases for Tutoring and Mentoring
* Diverse use cases for Scholarship and Grants
* Diverse use cases for Training and Courses

We should mention that our module is the  Training and Courses module of the above modules and link to the discussions of the same.

**Comment by techsavvyash** [comment]
The readme.md all mentions SkillEd: Trainings and Courses both in the heading and in the content. Will add this discussion in the quick link at the end of it.

**Comment by techsavvyash** [comment]
Refer: https://github.com/Samagra-Development/dsep/commit/d0039985b10cd841adde0347b597161e4aea6eaf
