### ISSUE TITLE
Setup the base monorepo using Turborepo

### ISSUE THREAD

**Issue by Bhavik-ag** [Samagra-Development/dsep#33]
## Description
- Set up the base monorepo using [Turborepo](https://turbo.build/repo) for the project. This includes setting up a monorepo combining frontend, backend and provider repositories.

   - https://github.com/Samagra-Development/dsep/
   - https://github.com/Samagra-Development/swayam-wrapper

**Note - We have a separate issue for setting up new frontend project** - https://github.com/Samagra-Development/dsep/issues/11.

## Project
DSEP: Trainings and Courses

## Product Name
DSEP

## Organization Name
Samagra | Transforming Governance

## Mentor(s)
@ChakshuGautam @Shruti3004 @techsavvyash 

## Tech Skills Needed
NextJS, ReactJS

## Complexity
Low

## Category
UI/UX enhancements

## Sub Category
Accessibility

## Domain
Others

**Comment by Anurag607** [comment]
@techsavvyash, I would like to work on this issue. Please assign it to me!

**Comment by Bhavik-ag** [comment]
Heyy @techsavvyash I will collaborate with @Anurag607 to resolve this issue simultaneously working on #11 .
